services:
  helm:
    image: alpine/helm:3.11.1
    container_name: helm
    volumes:
      - ./kind:/config:rw
      - ./helm:/apps
    environment:
      - KUBECONFIG=/config/kubeconfig.yaml
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    restart: unless-stopped

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: always
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data:

networks:
  kind-net:
    driver: bridge
