apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}-config
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMapData }}
  {{ $key }}: |-
    {{ $value | nindent 4 }}
  {{- end }}