apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}-secret
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value }}
  {{- end }}