replicaCount: 1

image:
  repository: ghcr.io/alex-carvalho/sandbox/spring-web-3-j21
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
