# Prometheus Helm chart values

# Server configurations
server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  persistentVolume:
    enabled: true
    size: 8Gi

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  # Service configuration
  service:
    type: ClusterIP

  # Additional scrape configurations
  extraScrapeConfigs: |
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

    - job_name: 'jenkins'
      metrics_path: /prometheus
      static_configs:
        - targets: ['jenkins.infrastructure.svc.cluster.local:8080']

# Alertmanager configurations
alertmanager:
  persistentVolume:
    enabled: true
    size: 2Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Service configuration
  service:
    type: ClusterIP

  # Alert configuration
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'

# Node exporter configurations
nodeExporter:
  enabled: false

# Pushgateway configurations
pushgateway:
  enabled: true

# kube-state-metrics configurations
kubeStateMetrics:
  enabled: true

# Service account configurations
serviceAccounts:
  server:
    create: true
  alertmanager:
    create: true
  nodeExporter:
    create: false
  pushgateway:
    create: true
